### ISSUE TITLE
Cannot find module relay-compiler/lib/transforms/RelayMaskTransform 

### ISSUE THREAD

**Issue by smmoosavi** [relay-tools/relay-compiler-language-typescript#153]
`relay-compiler-language-typescript@9.0.0` dosn't work with `relay-compiler@7.0.0`
```
Error: Cannot find module 'relay-compiler/lib/transforms/RelayMaskTransform'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path-to-project/node_modules/relay-compiler-language-typescript/lib/TypeScriptGenerator.js:47:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

```
├─ relay-compiler-language-typescript@9.0.0
├─ relay-compiler@7.0.0
```

**Comment by smmoosavi** [comment]
duplicate of #151
